# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
