# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
